// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import {getFirestore,collection,addDoc} from "firebase/firestore";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBpYU0RfznhuKyVS0CqCwaOeZwF0iVQJfM",
  authDomain: "my-first-poject-edfda.firebaseapp.com",
  projectId: "my-first-poject-edfda",
  storageBucket: "my-first-poject-edfda.appspot.com",
  messagingSenderId: "825431850072",
  appId: "1:825431850072:web:6eabc3ea1ca6a6c553de2d"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
// console.log(app);


const db = getFirestore(app);
// console.log(db);

// addDoc(collection(db,"users"),{
//       name:"aung aung",
//       city:"yangon",
//       age:20
// });


// display autoGenerated id after data set
addDoc(collection(db,"users"),{
        name:"aung aung",
        city:"yangon",
        age:20
}).then(docRef=>{
   console.log(docRef.id);
}).catch(error=>{
  console.log(error);
})


// Error for writing
// PERMISSION_DENIED


// Error for writing(Solved)
// Rules > allow read, write: if true;  > Publish







// =>Create Database 
// https://console.firebase.google.com/u/0/ > Build > Firestore Database > click "Create Database"
// Database ID = {default}
// Location = asia-southease1 (Singapore)
// click "Next" > click "Start in production mode" > click "create"


